---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - serviceaccounts
  - services
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - operator.openstack.org
  resources:
  - openstacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.openstack.org
  resources:
  - openstacks/finalizers
  verbs:
  - update
- apiGroups:
  - operator.openstack.org
  resources:
  - openstacks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  - installplans
  - operators
  - subscriptions
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - rabbitmq.com
  resources:
  - bindings
  - exchanges
  - federations
  - operatorpolicies
  - permissions
  - policies
  - queues
  - schemareplications
  - shovels
  - superstreams
  - topicpermissions
  - users
  - vhosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - bindings/finalizers
  - exchanges/finalizers
  - federations/finalizers
  - operatorpolicies/finalizers
  - permissions/finalizers
  - policies/finalizers
  - queues/finalizers
  - schemareplications/finalizers
  - shovels/finalizers
  - superstreams/finalizers
  - topicpermissions/finalizers
  - users/finalizers
  - vhosts/finalizers
  verbs:
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - bindings/status
  - exchanges/status
  - federations/status
  - operatorpolicies/status
  - permissions/status
  - policies/status
  - queues/status
  - schemareplications/status
  - shovels/status
  - superstreams/status
  - topicpermissions/status
  - users/status
  - vhosts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters/status
  verbs:
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - '*'
